title: Test
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "SemperFu"
  email: "someone@somewebsite.somedomain"
  url: "https://cdbbs.net"
baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SemperFu"
year : "2018"

theme: jekyll-theme-hacker
